spring:
  profiles:
    active: dev
swagger:
  ui:
    title: 用户管理
    contact: 齐欢
    version: 1.0
    description: 用户管理
    group: qi
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
pomelo:
#  address: ws://192.168.1.185:33009
  address: ws://101.37.161.243:33009